### ISSUE TITLE
I have a problem in ckeditor4-detail ,but it is readonly

### ISSUE THREAD

**Issue by myth984** [akilli/cms#39]
Thanks again, I can't use ckeditor4-detail https://github.com/akilli/ckeditor4-detail.

I found a problem in line 72.

![image](https://user-images.githubusercontent.com/43159834/112113144-6868a600-8bf1-11eb-85bc-6e034e5dbde1.png)

can't find api, can you help me?

**Comment by akilli** [comment]
Hi @myth984 ,

https://github.com/akilli/ckeditor4-detail has nothing to do with the cms. Besides that it is an archived project. Anyhow, the api you are looking for is https://github.com/akilli/ckeditor4-api
